server.port: 8080

logging:
  level:
    root: INFO
    com.be-lecoingameover: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: lecoingameoverdb
      username: root
      password: password
      authentication-database: admin

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5


---
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      host: mongo
      port: 27017
      database: lecoingameoverdb
      username: root
      password: password
      authentication-database: admin

okta:
  oauth2:
    issuer: https://dev-pgf67fhh21tkyd1v.us.auth0.com/
    audience: http://api.LeCoinGameOver.com

auth0:
  domain: dev-pgf67fhh21tkyd1v.us.auth0.com
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: https://dev-pgf67fhh21tkyd1v.us.auth0.com/api/v2/