server:
  port: 8080

logging:
  level:
    root: INFO
    com.be-lecoingameover: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}  # Use MongoDB Atlas from .env

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5
