import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/consoles');
  await expect(page.getByRole('button', { name: 'Add Console' })).toBeVisible();
  await page.getByRole('button', { name: 'Add Console' }).click();
  await expect(page.locator('input[name="consoleName"]')).toBeVisible();
  await page.locator('input[name="consoleName"]').click();
  await page.locator('input[name="consoleName"]').fill('t');
  await expect(page.locator('input[name="releaseDate"]')).toBeVisible();
  await page.locator('input[name="releaseDate"]').press('ArrowRight');
  await expect(page.locator('input[name="price"]')).toBeVisible();
  await page.locator('input[name="price"]').click();
  await page.locator('input[name="price"]').fill('01');
  await expect(page.locator('input[name="quantityInStock"]')).toBeVisible();
  await page.locator('input[name="quantityInStock"]').click();
  await page.locator('input[name="quantityInStock"]').fill('02');
  await expect(page.locator('input[name="company"]')).toBeVisible();
  await page.locator('input[name="company"]').click();
  await page.locator('input[name="company"]').fill('T');
  await expect(page.getByRole('button', { name: 'Add' })).toBeVisible();
  await page.getByRole('button', { name: 'Add' }).click();
  await expect(page.getByRole('cell', { name: 'test', exact: true })).toBeVisible();
  await expect(page.getByRole('cell', { name: '-12-30' })).toBeVisible();
  await expect(page.getByRole('cell', { name: '$190.00' })).toBeVisible();
  await expect(page.getByRole('cell', { name: '200', exact: true }).nth(1)).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Test Company' })).toBeVisible();
  await expect(page.locator('tbody')).toContainText('test');
  await expect(page.locator('tbody')).toContainText('2005-12-30');
  await expect(page.locator('tbody')).toContainText('$190.00');
  await expect(page.locator('tbody')).toContainText('200');
  await expect(page.locator('tbody')).toContainText('Test Company');
});