
application:
  name: GameOverStore
  environment: development
  version: 1.0.0

backend:
  port: 8080
#  database:
#    uri: mongodb://mongo1:27017/gameoverstore
  api:
    base_url: http://localhost:8080/api
  spring:
    profiles: docker

frontend:
  port: 3000
  backend_url: http://localhost:8080
  app_title: GameOver Storefront




logging:
  level: INFO
  file: logs/app.log

spring:
  config:
    activate:
      on-profile: docker


data:
  mongodb:
    hostname: mongo1
    port: 27017
    database: gameoverstore
    username: user
    password: pwd
    authentication-database: admin