name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Backend Docker image
      run: docker build ./be-lecoingameover --file ./be-lecoingameover/Dockerfile --tag backend-image:$(date +%s)

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Frontend Docker image
      run: docker build ./fe-lecoingameover --file ./fe-lecoingameover/Dockerfile --tag frontend-image:$(date +%s)
